export const SIGN_UP_SUCCESSFUL="SIGN_UP_SUCCESSFUL";
export const SIGN_IN_FAILED="SIGN_IN_FAILED";
export const LOGIN_SUCCESSFUL="LOGIN_SUCCESSFUL";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const LOGOUT="LOGOUT"
export const GET_USERS="GET_USERS"
